# -*- coding: utf-8 -*-
"""
/***************************************************************************
 fieldtype
                                 A QGIS plugin
 AIC land type classifier
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-08-20
        copyright            : (C) 2021 by aic
        email                : mohamed.rehan@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load fieldtype class from file fieldtype.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .landtype import fieldtype
    return fieldtype(iface)
