const govs = [
  { gov: "Egypt", url: "#" },
  { gov: "Cairo", url: "#" },
  { gov: "Cairo", url: "#" },
  { gov: "Cairo", url: "#" },
  { gov: "Cairo", url: "#" },
  { gov: "Cairo", url: "#" },
  { gov: "Cairo", url: "#" },
  { gov: "Cairo", url: "#" },
  { gov: "Cairo", url: "#" },
  { gov: "Cairo", url: "#" },
  { gov: "Cairo", url: "#" },
  { gov: "Cairo", url: "#" },
  { gov: "Cairo", url: "#" },
  { gov: "Cairo", url: "#" },
  { gov: "Cairo", url: "#" },
  { gov: "Cairo", url: "#" },
  { gov: "Cairo", url: "#" },
  { gov: "Cairo", url: "#" },
  { gov: "Cairo", url: "#" },
  { gov: "Cairo", url: "#" },
  { gov: "Cairo", url: "#" },
  { gov: "Cairo", url: "#" },
  { gov: "Cairo", url: "#" },
  { gov: "Cairo", url: "#" },
  { gov: "Cairo", url: "#" },
  { gov: "Cairo", url: "#" },
  { gov: "Cairo", url: "#" },
  { gov: "Cairo", url: "#" },
  { gov: "Cairo", url: "#" },
];

const dates = [
  { url: "#", date: "27-5-2020" },
  { url: "#", date: "27-5-2020" },
  { url: "#", date: "27-5-2020" },
  { url: "#", date: "27-5-2020" },
  { url: "#", date: "27-5-2020" },
  { url: "#", date: "27-5-2020" },
  { url: "#", date: "27-5-2020" },
  { url: "#", date: "27-5-2020" },
  { url: "#", date: "27-5-2020" },
  { url: "#", date: "27-5-2020" },
  { url: "#", date: "27-5-2020" },
  { url: "#", date: "27-5-2020" },
  { url: "#", date: "27-5-2020" },
  { url: "#", date: "27-5-2020" },
];

const cities = [
  "Abohomos",
  "Nasrcity",
  "Nasrcity",
  "Nasrcity",
  ,
  "Nasrcity",
  ,
  "Nasrcity",
  "Nasrcity",
  "Nasrcity",
  "Nasrcity",
  "Nasrcity",
  "Nasrcity",
  "Nasrcity",
  "Nasrcity",
  "Nasrcity",
  "Nasrcity",
  "Nasrcity",
  "Nasrcity",
  "Nasrcity",
  "Nasrcity",
];
export { govs, dates, cities };
